
import { ResumeData } from './types';

export const INITIAL_DATA: ResumeData = {
  template: 'modern',
  personalInfo: {
    fullName: 'IDIABY IBRAHIM',
    role: 'FULL STACK DEVELOPER',
    email: 'ibkhalidworld@gmail.com',
    phone: '+224 613 12 34 56',
    linkedin: 'linkedin.com/in/idiabyibrahim',
    location: 'Conakry, Guinea',
    summary: 'Full Stack Developer with over 6 years of experience in building user-centric digital products. Passionate about solving complex problems through elegant design solutions. Proven track record of leading design teams and delivering high-impact projects.',
    photoUrl: 'https://picsum.photos/200/200',
  },
  experiences: [
    {
      id: '1',
      company: 'Freelance',
      title: 'Lead Product Designer',
      location: 'Conakry, Guinea',
      startDate: '2020',
      endDate: 'Present',
      description: '• Spearheaded the redesign of the core platform, increasing user engagement by 40%.\n• Mentored a team of 4 junior designers.\n• Collaborated closely with engineering and product managers to define roadmap. • Spearheaded the redesign of the core platform, increasing user engagement by 40%.\n• Mentored a team of 4 junior designers.\n• Collaborated closely with engineering and product managers to define roadmap.',
    }, 
  ],
  education: [
    {
      id: '1',
      school: 'MIT',
      degree: 'Bachelor of Science in Computer Science',
      startDate: '2018',
      endDate: '2022',
    },
  ],
  skills: ['React', 'Node.js', 'MongoDB', 'Express', 'HTML/CSS', 'JavaScript', 'Python'],
  languages: [
    { id: '1', language: 'English', proficiency: 5 },
    { id: '2', language: 'French', proficiency: 3 },
    { id: '3', language: 'Arabic', proficiency: 2 },
  ],
  achievements: [
    {
      id: '1',
      title: 'Best Full Stack Developer Award 2025',
      description: 'Awarded by the Global Full Stack Developer Association for innovation in web development.',
    },
  ],
  courses: ['Advanced React (Udemy)', 'Advanced Node.js (Udemy)', 'Advanced MongoDB (Udemy)', 'Advanced Express (Udemy)'],
  interests: ['Photography', 'Traveling', 'Hiking', 'Cooking'],
  sectionOrder: [
    'experience',
    'education',
    'skills',
    'languages',
    'achievements',
    'courses',
    'interests'
  ],
  coverLetter: {
    recipientName: 'IDIABY IBRAHIM  ',
    companyName: 'Acme Corp',
    jobTitle: 'Full Stack Developer',
    body: `Dear IDIABY IBRAHIM,

I am writing to express my strong interest in the Full Stack Developer position at Acme Corp. With over 6 years of experience in web development and a proven track record of leading development teams to deliver high-impact digital products, I am confident in my ability to contribute to your team's success.

Throughout my career, I have honed my skills in web development, backend development, and database management. At Tech Solutions Inc., I spearheaded a platform redesign that resulted in a 40% increase in user engagement. I am passionate about creating elegant, user-centric solutions that solve complex business problems.

I admire Acme Corp's commitment to innovation and would welcome the opportunity to bring my expertise and leadership to your development team. Thank you for considering my application. I look forward to the possibility of discussing how my skills align with your needs.

Sincerely,
IDIABY IBRAHIM`
  }
};

export const TRANSLATIONS = {
  en: {
    personalInfo: "Personal Information",
    experience: "Experience",
    education: "Education",
    skills: "Skills",
    languages: "Languages",
    achievements: "Key Achievements",
    courses: "Courses",
    interests: "Interests",
    fullName: "Full Name",
    role: "Job Title / Role",
    email: "Email",
    phone: "Phone",
    location: "Location",
    linkedin: "LinkedIn URL",
    photo: "Photo",
    summary: "Summary",
    company: "Company",
    title: "Title",
    startDate: "Start Date",
    endDate: "End Date",
    description: "Description (Bullets)",
    school: "School",
    degree: "Degree",
    language: "Language",
    proficiency: "Proficiency",
    achievementTitle: "Achievement Title",
    autoWrite: "Auto-Write",
    writing: "Writing...",
    enhance: "Enhance",
    enhancing: "Enhancing...",
    addExperience: "Add Experience",
    addEducation: "Add Education",
    addSkill: "Add Skill",
    addLanguage: "Add Language",
    addAchievement: "Add Achievement",
    addCourse: "Add Course",
    addInterest: "Add Interest",
    print: "Download PDF",
    beginner: "Beginner",
    elementary: "Elementary",
    intermediate: "Intermediate",
    advanced: "Advanced",
    native: "Native",
    contacts: "Contacts",
    selectTemplate: "Select Template",
    modern: "Modern Teal",
    classic: "Classic Serif",
    minimal: "Minimal Clean",
    professional: "Professional Blue",
    elegant: "Elegant",
    creative: "Creative Hex",
    editorTitle: "Editor",
    savePdf: "Save PDF",
    printTooltip: "Select 'Save as PDF' in the print dialog.",
    placeholderDesc: "• Description...",
    placeholderImgUrl: "Image URL",
    about: "About",
    level: "Level",
    dragReorder: "Drag to reorder",
    viewResume: "Resume",
    viewCoverLetter: "Cover Letter",
    coverLetterDetails: "Job Details",
    recipientName: "Hiring Manager Name",
    targetCompany: "Target Company",
    targetRole: "Target Job Title",
    coverLetterBody: "Cover Letter Content",
    generateCoverLetter: "Generate with AI",
    generating: "Generating...",
  },
  fr: {
    personalInfo: "Informations Personnelles",
    experience: "Expérience",
    education: "Formation",
    skills: "Compétences",
    languages: "Langues",
    achievements: "Réalisations Clés",
    courses: "Cours",
    interests: "Centres d'intérêt",
    fullName: "Nom Complet",
    role: "Poste / Titre",
    email: "Email",
    phone: "Téléphone",
    location: "Lieu",
    linkedin: "URL LinkedIn",
    photo: "Photo",
    summary: "Résumé",
    company: "Entreprise",
    title: "Titre",
    startDate: "Date de début",
    endDate: "Date de fin",
    description: "Description (Puces)",
    school: "École",
    degree: "Diplôme",
    language: "Langue",
    proficiency: "Niveau",
    achievementTitle: "Titre de la réalisation",
    autoWrite: "Rédiger",
    writing: "Rédaction...",
    enhance: "Améliorer",
    enhancing: "Amélioration...",
    addExperience: "Ajouter Expérience",
    addEducation: "Ajouter Formation",
    addSkill: "Ajouter Compétence",
    addLanguage: "Ajouter Langue",
    addAchievement: "Ajouter Réalisation",
    addCourse: "Ajouter Cours",
    addInterest: "Ajouter Intérêt",
    print: "Télécharger PDF",
    beginner: "Débutant",
    elementary: "Élémentaire",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    native: "Langue Maternelle",
    contacts: "Contacts",
    selectTemplate: "Choisir le modèle",
    modern: "Moderne Sarcelle",
    classic: "Classique Serif",
    minimal: "Minimal Épuré",
    professional: "Professionnel Bleu",
    elegant: "Élégant",
    creative: "Créatif Hex",
    editorTitle: "Éditeur",
    savePdf: "Enregistrer PDF",
    printTooltip: "Sélectionnez 'Enregistrer au format PDF'.",
    placeholderDesc: "• Description...",
    placeholderImgUrl: "URL de l'image",
    about: "À propos",
    level: "Niveau",
    dragReorder: "Glisser pour réorganiser",
    viewResume: "CV",
    viewCoverLetter: "Lettre de Motivation",
    coverLetterDetails: "Détails du Poste",
    recipientName: "Nom du Recruteur",
    targetCompany: "Entreprise Cible",
    targetRole: "Titre du Poste Cible",
    coverLetterBody: "Contenu de la Lettre",
    generateCoverLetter: "Générer avec l'IA",
    generating: "Génération...",
  }
};
