
import { ResumeData, ThemeConfig } from './types';

export const DEFAULT_THEME: ThemeConfig = {
  primary: '#059669',
  secondary: '#34d399',
  accent: '#0f172a',
  background: '#ffffff',
  text: '#0f172a'
};

export const INITIAL_DATA: ResumeData = {
  template: 'modern',
  theme: DEFAULT_THEME,
  personalInfo: {
    fullName: 'DIABY IBRAHIM',
    role: 'FULL STACK DEVELOPER',
    email: 'ibkhalidworld@gmail.com',
    phone: '+224 613 12 34 56',
    linkedin: 'linkedin.com/in/idiabyibrahim',
    location: 'Conakry, Guinea',
    summary: 'Full Stack Developer with over 6 years of experience in building user-centric digital products. Passionate about solving complex problems through elegant design solutions. Proven track record of leading design teams and delivering high-impact projects.',
    photoUrl: 'https://picsum.photos/200/200',
  },
  experiences: [
    {
      id: '1',
      company: 'Freelance',
      title: 'Lead Product Designer',
      location: 'Conakry, Guinea',
      startDate: '2020',
      endDate: 'Present',
      description: '• Spearheaded the redesign of the core platform, increasing user engagement by 40%.\n• Mentored a team of 4 junior designers.\n• Collaborated closely with engineering and product managers to define roadmap. • Spearheaded the redesign of the core platform, increasing user engagement by 40%.\n• Mentored a team of 4 junior designers.\n• Collaborated closely with engineering and product managers to define roadmap.',
    }, 
  ],
  education: [
    {
      id: '1',
      school: 'MIT',
      degree: 'Bachelor of Science in Computer Science',
      startDate: '2018',
      endDate: '2022',
    },
  ],
  skills: ['React', 'Node.js', 'MongoDB', 'Express', 'HTML/CSS', 'JavaScript', 'Python'],
  languages: [
    { id: '1', language: 'English', proficiency: 5 },
    { id: '2', language: 'French', proficiency: 3 },
    { id: '3', language: 'Arabic', proficiency: 2 },
  ],
  achievements: [
    {
      id: '1',
      title: 'Best Full Stack Developer Award 2025',
      description: 'Awarded by the Global Full Stack Developer Association for innovation in web development.',
    },
  ],
  courses: ['Advanced React (Udemy)', 'Advanced Node.js (Udemy)', 'Advanced MongoDB (Udemy)', 'Advanced Express (Udemy)'],
  interests: ['Photography', 'Traveling', 'Hiking', 'Cooking'],
  sectionOrder: [
    'experience',
    'education',
    'skills',
    'languages',
    'achievements',
    'courses',
    'interests'
  ],
  coverLetter: {
    recipientName: 'IDIABY IBRAHIM  ',
    companyName: 'Acme Corp',
    jobTitle: 'Full Stack Developer',
    body: `Dear IDIABY IBRAHIM,

I am writing to express my strong interest in the Full Stack Developer position at Acme Corp. With over 6 years of experience in web development and a proven track record of leading development teams to deliver high-impact digital products, I am confident in my ability to contribute to your team's success.

Throughout my career, I have honed my skills in web development, backend development, and database management. At Tech Solutions Inc., I spearheaded a platform redesign that resulted in a 40% increase in user engagement. I am passionate about creating elegant, user-centric solutions that solve complex business problems.

I admire Acme Corp's commitment to innovation and would welcome the opportunity to bring my expertise and leadership to your development team. Thank you for considering my application. I look forward to the possibility of discussing how my skills align with your needs.

Sincerely,
IDIABY IBRAHIM`
  }
};

export const TRANSLATIONS = {
  en: {
    personalInfo: "Personal Information",
    experience: "Experience",
    education: "Education",
    skills: "Skills",
    languages: "Languages",
    achievements: "Key Achievements",
    courses: "Courses",
    interests: "Interests",
    fullName: "Full Name",
    role: "Job Title / Role",
    email: "Email",
    phone: "Phone",
    location: "Location",
    linkedin: "LinkedIn URL",
    photo: "Photo",
    summary: "Summary",
    company: "Company",
    title: "Title",
    startDate: "Start Date",
    endDate: "End Date",
    description: "Description (Bullets)",
    school: "School",
    degree: "Degree",
    language: "Language",
    proficiency: "Proficiency",
    achievementTitle: "Achievement Title",
    autoWrite: "Auto-Write",
    autoWriteTooltip: "Auto-Write (1 credit)",
    writing: "Writing...",
    enhance: "Enhance",
    enhanceTooltip: "Enhance with AI (1 credit)",
    enhancing: "Enhancing...",
    addExperience: "Add Experience",
    addEducation: "Add Education",
    addSkill: "Add Skill",
    addLanguage: "Add Language",
    addAchievement: "Add Achievement",
    addCourse: "Add Course",
    addInterest: "Add Interest",
    print: "Download PDF",
    beginner: "Beginner",
    elementary: "Elementary",
    intermediate: "Intermediate",
    advanced: "Advanced",
    native: "Native",
    contacts: "Contacts",
    selectTemplate: "Select Template",
    modern: "Modern Teal",
    classic: "Classic Serif",
    minimal: "Minimal Clean",
    professional: "Professional Blue",
    elegant: "Elegant",
    creative: "Creative Hex",
    editorTitle: "Editor",
    editor: "Editor",
    preview: "Preview",
    savePdf: "Save PDF",
    printTooltip: "Select 'Save as PDF' in the print dialog.",
    placeholderDesc: "• Description...",
    placeholderImgUrl: "Image URL",
    about: "About",
    level: "Level",
    dragReorder: "Drag to reorder",
    viewResume: "Resume",
    viewCoverLetter: "Cover Letter",
    coverLetterDetails: "Job Details",
    recipientName: "Hiring Manager Name",
    targetCompany: "Target Company",
    targetRole: "Target Job Title",
    coverLetterBody: "Cover Letter Content",
    generateCoverLetter: "Generate with AI",
    generateCoverLetterTooltip: "Generate with AI (1 credit)",
    generating: "Generating...",
    coverLetterInstructions: "Fill in the job details below, then click \"Generate with AI\" to create a personalized cover letter using all your resume information (experiences, skills, education, achievements, etc.).",
    hiringFor: "Hiring for",
    coverLetterPlaceholder: "(Cover letter content will appear here. Use the editor to write or generate one.)",
    hiringManager: "Hiring Manager",
    dear: "Dear",
    sincerely: "Sincerely",
    themeColors: "Template Colors",
    primaryColor: "Primary",
    secondaryColor: "Secondary",
    accentColor: "Accent",
    backgroundColor: "Background",
    textColor: "Text",
    authSignIn: "Sign In",
    authSignOut: "Sign Out",
    authWelcome: "Welcome back!",
    authEmail: "Email",
    authPassword: "Password",
    authName: "Full name",
    authHaveAccount: "Already have an account?",
    authNoAccount: "Need an account?",
    checkoutTitle: "Checkout",
    checkoutDescription: "Unlock pro downloads and premium templates.",
    planFree: "Free",
    planPro: "Pro",
    planPrice: "$12",
    startCheckout: "Start checkout",
    upgrade: "Upgrade",
    proActive: "Pro active",
    paymentInfo: "Payment details (demo)",
    cardNumber: "Card number",
    expiry: "Expiry",
    cvc: "CVC",
    completePurchase: "Complete purchase",
    loginToCheckout: "Sign in to continue to checkout",
    signInToDownload: "Sign in to download",
    upgradeToUnlock: "Upgrade to Pro to unlock AI features",
    credits: "Credits",
    currentCredits: "Current Credits",
    buyCredits: "Buy Credits",
    creditUsage: "Credit Usage",
    creditUsageInfo: "Resume Download: 2 credits | Cover Letter Download: 2 credits | AI Features: 1 credit each (only charged on success)",
    resumeDownloadCost: "Resume Download",
    coverLetterDownloadCost: "Cover Letter Download",
    aiFeaturesCost: "AI Features",
    creditsText: "credits",
    creditText: "credit",
    each: "each",
    aiCreditsNote: "AI credits only charged on successful operations",
    processing: "Processing...",
    insufficientCredits: "Insufficient credits. Please purchase more.",
    bonus: "Bonus",
    bonusCredits: "Bonus Credits",
    totalCredits: "Total Credits",
    base: "base",
    selectedPackage: "Selected Package",
    totalAmount: "Total Amount"
  },
  fr: {
    personalInfo: "Informations Personnelles",
    experience: "Expérience",
    education: "Formation",
    skills: "Compétences",
    languages: "Langues",
    achievements: "Réalisations Clés",
    courses: "Cours",
    interests: "Centres d'intérêt",
    fullName: "Nom Complet",
    role: "Poste / Titre",
    email: "Email",
    phone: "Téléphone",
    location: "Lieu",
    linkedin: "URL LinkedIn",
    photo: "Photo",
    summary: "Résumé",
    company: "Entreprise",
    title: "Titre",
    startDate: "Date de début",
    endDate: "Date de fin",
    description: "Description (Puces)",
    school: "École",
    degree: "Diplôme",
    language: "Langue",
    proficiency: "Niveau",
    achievementTitle: "Titre de la réalisation",
    autoWrite: "Rédiger",
    autoWriteTooltip: "Rédiger (1 crédit)",
    writing: "Rédaction...",
    enhance: "Améliorer",
    enhanceTooltip: "Améliorer avec l'IA (1 crédit)",
    enhancing: "Amélioration...",
    addExperience: "Ajouter Expérience",
    addEducation: "Ajouter Formation",
    addSkill: "Ajouter Compétence",
    addLanguage: "Ajouter Langue",
    addAchievement: "Ajouter Réalisation",
    addCourse: "Ajouter Cours",
    addInterest: "Ajouter Intérêt",
    print: "Télécharger PDF",
    beginner: "Débutant",
    elementary: "Élémentaire",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    native: "Langue Maternelle",
    contacts: "Contacts",
    selectTemplate: "Choisir le modèle",
    modern: "Moderne Sarcelle",
    classic: "Classique Serif",
    minimal: "Minimal Épuré",
    professional: "Professionnel Bleu",
    elegant: "Élégant",
    creative: "Créatif Hex",
    editorTitle: "Éditeur",
    editor: "Éditeur",
    preview: "Aperçu",
    savePdf: "Enregistrer PDF",
    printTooltip: "Sélectionnez 'Enregistrer au format PDF'.",
    placeholderDesc: "• Description...",
    placeholderImgUrl: "URL de l'image",
    about: "À propos",
    level: "Niveau",
    dragReorder: "Glisser pour réorganiser",
    viewResume: "CV",
    viewCoverLetter: "Lettre de Motivation",
    coverLetterDetails: "Détails du Poste",
    recipientName: "Nom du Recruteur",
    targetCompany: "Entreprise Cible",
    targetRole: "Titre du Poste Cible",
    coverLetterBody: "Contenu de la Lettre",
    generateCoverLetter: "Générer avec l'IA",
    generateCoverLetterTooltip: "Générer avec l'IA (1 crédit)",
    generating: "Génération...",
    coverLetterInstructions: "Remplissez les détails du poste ci-dessous, puis cliquez sur \"Générer avec l'IA\" pour créer une lettre de motivation personnalisée en utilisant toutes les informations de votre BaraCV (expériences, compétences, formation, réalisations, etc.).",
    hiringFor: "Recrutement pour",
    coverLetterPlaceholder: "(Le contenu de la lettre de motivation apparaîtra ici. Utilisez l'éditeur pour écrire ou en générer une.)",
    hiringManager: "Responsable du Recrutement",
    dear: "Cher/Chère",
    sincerely: "Cordialement",
    themeColors: "Couleurs du modèle",
    primaryColor: "Principale",
    secondaryColor: "Secondaire",
    accentColor: "Accent",
    backgroundColor: "Arrière-plan",
    textColor: "Texte",
    authSignIn: "Se connecter",
    authSignOut: "Se déconnecter",
    authWelcome: "Bon retour !",
    authEmail: "Email",
    authPassword: "Mot de passe",
    authName: "Nom complet",
    authHaveAccount: "Vous avez déjà un compte ?",
    authNoAccount: "Besoin d'un compte ?",
    checkoutTitle: "Paiement",
    checkoutDescription: "Débloquez les téléchargements pro et les modèles premium.",
    planFree: "Gratuit",
    planPro: "Pro",
    planPrice: "12 $",
    startCheckout: "Commencer le paiement",
    upgrade: "Acheter ",
    proActive: "Pro actif",
    paymentInfo: "Détails de paiement (démo)",
    cardNumber: "Numéro de carte",
    expiry: "Expiration",
    cvc: "CVC",
    completePurchase: "Finaliser l'achat",
    loginToCheckout: "Connectez-vous pour payer",
    signInToDownload: "Connectez-vous pour télécharger",
    upgradeToUnlock: "Passez à Pro pour débloquer les fonctionnalités IA",
    credits: "Crédits",
    currentCredits: "Crédits Actuels",
    buyCredits: "Acheter des Crédits",
    creditUsage: "Utilisation des Crédits",
    creditUsageInfo: "Téléchargement CV: 2 crédits | Téléchargement Lettre: 2 crédits | Fonctionnalités IA: 1 crédit chacune (facturé uniquement en cas de succès)",
    resumeDownloadCost: "Téléchargement CV",
    coverLetterDownloadCost: "Téléchargement Lettre",
    aiFeaturesCost: "Fonctionnalités IA",
    creditsText: "crédits",
    creditText: "crédit",
    each: "chacune",
    aiCreditsNote: "Les crédits IA ne sont facturés qu'en cas de succès",
    processing: "Traitement...",
    insufficientCredits: "Crédits insuffisants. Veuillez en acheter plus.",
    bonus: "Bonus",
    bonusCredits: "Crédits Bonus",
    totalCredits: "Total des Crédits",
    base: "de base",
    selectedPackage: "Forfait Sélectionné",
    totalAmount: "Montant Total",
    landingTitle: "Créez des BaraCV et Lettres de Motivation Professionnels",
    landingSubtitle: "Créez des BaraCV et lettres de motivation époustouflants en quelques minutes avec l'assistance de l'IA",
    landingGetStarted: "Commencer",
    landingFeaturesTitle: "Pourquoi Choisir BaraCV?",
    landingFeaturesSubtitle: "Tout ce dont vous avez besoin pour créer un BaraCV remarquable",
    landingFeature1Title: "Modèles Professionnels",
    landingFeature1Desc: "Choisissez parmi plusieurs modèles magnifiques et compatibles ATS conçus par des professionnels",
    landingFeature2Title: "Rédaction Assistée par IA",
    landingFeature2Desc: "Laissez l'IA améliorer vos descriptions et générer des lettres de motivation convaincantes",
    landingFeature3Title: "Couleurs Personnalisables",
    landingFeature3Desc: "Personnalisez votre BaraCV avec des schémas de couleurs personnalisés pour correspondre à votre style",
    landingFeature4Title: "Téléchargement Facile",
    landingFeature4Desc: "Téléchargez votre BaraCV en PDF en un clic, prêt à partager",
    landingHowItWorks: "Comment Ça Marche",
    landingHowItWorksDesc: "Créez votre BaraCV parfait en trois étapes simples",
    landingStep1: "Remplissez vos informations",
    landingStep2: "Personnalisez votre modèle",
    landingStep3: "Téléchargez votre BaraCV",
    landingSupportTitle: "Besoin d'Aide?",
    landingSupportDesc: "Notre équipe de support est là pour vous aider. Contactez-nous à tout moment!",
    landingReadyToStart: "Prêt à Créer Votre BaraCV?",
    landingReadyToStartDesc: "Rejoignez des milliers de professionnels qui font confiance à BaraCV pour leurs BaraCV"
  }
};
